### ISSUE TITLE
Build download ?

### ISSUE THREAD

**Issue by KaKi87** [MiniDigger/MiniLauncher#12]
Hello,

Screenshots shows your launcher working on Ubuntu, is there a distributable build of it yet ?

Thanks !

**Comment by mikroskeem** [comment]
This project has been stale for about 2 years. No.

**Comment by MiniDigger** [comment]
I am not even sure if it still works or ever worked outside of an IDE.
this was a project I exclusively worked on in boring uni classes :D

if somebody wants to make sure this still works and setting up a github actions flow, I will happily accept a PR :)

**Comment by KaKi87** [comment]
I understand ^^
I've been searching for an open source Java Minecraft launcher for Linux but I guess I should give up on that idea lol.

**Comment by MiniDigger** [comment]
this could be very well be that, I just have no time to dedicate to this project right now, as my todo list is infinite already. 

I would be open to finish this as part of a commission tho I guess

**Comment by KaKi87** [comment]
> my todo list is infinite already

I definitely can relate to that xD

Best wishes for the future. ;)
