### ISSUE TITLE
build incompatibility with gradle 7.1 and java 16

### ISSUE THREAD

**Issue by MaxBr5** [MiniDigger/MiniLauncher#15]
<pre>Please make the build compatible with java 16
and gradle 7.1 for I need gradle 7 to build on java 16
and you need java 16 to build mods for 1.17.</pre>
___
<h2>===Build Information===</h2>
<pre>
Initialized native services in: C:\Users\MaxBr\.gradle\native
The client will now receive all logging from the daemon (pid: 8396). The daemon log file: C:\Users\MaxBr\.gradle\daemon\7.1-20210528181608+0000\daemon-8396.out.log
Starting 3rd build in daemon [uptime: 2 mins 52.801 secs, performance: 99%, non-heap usage: 38% of 256 MiB]
Using 4 worker leases.
Now considering [C:\Users\MaxBr\MiniLauncher] as hierarchies to watch
Not watching anything anymore
Watching the file system is enabled if available
Starting Build
Settings evaluated using settings file 'C:\Users\MaxBr\MiniLauncher\settings.gradle.kts'.
Projects loaded. Root project using build file 'C:\Users\MaxBr\MiniLauncher\build.gradle.kts'.
Included projects: [root project 'MinecraftLauncher', project ':JMCCC', project ':JMCCC/jmccc', project ':JMCCC/jmccc-mcdownloader', project ':JMCCC/jmccc-mojang-api', project ':JMCCC/jmccc-yggdrasil-authenticator', project ':launcher', project ':renderer']

> Configure project :
Evaluating root project 'MinecraftLauncher' using build file 'C:\Users\MaxBr\MiniLauncher\build.gradle.kts'.

FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class org.jetbrains.kotlin.gradle.internal.KotlinSourceSetProviderImplKt
</pre>

**Comment by MaxBr5** [comment]
Tried updating kotlin like stackexchange.com wanted me to. Got this instead.
___
<pre>FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\MaxBr\MiniLauncher\build.gradle.kts' line: 4

* What went wrong:
An exception occurred applying plugin request [id: 'net.minecrell.licenser', version: '0.3']
> Failed to apply plugin 'net.minecrell.licenser'.
   > Could not set unknown property 'header' for extension 'base' of type org.gradle.api.plugins.internal.DefaultBasePluginExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s</pre>

**Comment by MiniDigger** [comment]
I don't plan on to put much time into this project, unless somebody PRs it. you can just compile the launcher with an older java and gradle version, what mods use doesn't matter, it will work fine.
